-- PRAGMA settings — set at connection time, not in migration
-- These are applied in state.rs when the pool is created

-- Users Table
-- Each Google account = one user row
-- google_id is the unique identifier from Google's OAuth2 response ("sub" field)
CREATE TABLE IF NOT EXISTS users (
    id          TEXT PRIMARY KEY,          -- UUID v4, generated by Rust
    google_id   TEXT NOT NULL UNIQUE,      -- Google OAuth2 "sub" claim
    email       TEXT NOT NULL UNIQUE,
    name        TEXT NOT NULL,
    avatar_url  TEXT,
    created_at  TEXT NOT NULL,             -- ISO 8601 UTC timestamp
    updated_at  TEXT NOT NULL
);

-- OAuth Tokens Table
-- Stores access + refresh tokens per user
-- Tokens are sensitive — encrypt at rest (see Section 6)
CREATE TABLE IF NOT EXISTS oauth_tokens (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    access_token    TEXT NOT NULL,
    refresh_token   TEXT,
    token_type      TEXT NOT NULL DEFAULT 'Bearer',
    expires_at      TEXT NOT NULL,         -- ISO 8601 UTC
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);

-- Links Table
-- Core entity: a saved URL
CREATE TABLE IF NOT EXISTS links (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    url             TEXT NOT NULL,
    title           TEXT,                  -- Auto-fetched or user-provided
    description     TEXT,                  -- Optional note about this link
    category        TEXT NOT NULL,         -- Auto-detected: "youtube", "instagram", etc.
    favicon_url     TEXT,
    is_favorite     INTEGER NOT NULL DEFAULT 0,  -- Boolean (0/1)
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);

-- Tags Table
-- Normalized tag store — tags are reusable across items
CREATE TABLE IF NOT EXISTS tags (
    id      TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name    TEXT NOT NULL,
    color   TEXT NOT NULL DEFAULT '#6366f1',  -- Hex color for UI display
    UNIQUE(user_id, name)
);

-- Link Tags Junction Table
-- Many-to-many between links and tags
CREATE TABLE IF NOT EXISTS link_tags (
    link_id TEXT NOT NULL REFERENCES links(id) ON DELETE CASCADE,
    tag_id  TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (link_id, tag_id)
);

-- Media Table
-- Stores images and videos — with OR without an associated link
CREATE TABLE IF NOT EXISTS media (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    link_id         TEXT REFERENCES links(id) ON DELETE SET NULL,  -- Optional association
    file_name       TEXT NOT NULL,
    file_path       TEXT NOT NULL,         -- Relative path inside the media storage dir
    file_size       INTEGER NOT NULL,      -- Bytes
    mime_type       TEXT NOT NULL,         -- e.g., "image/jpeg", "video/mp4"
    media_type      TEXT NOT NULL,         -- "image" or "video"
    note            TEXT,                  -- Optional user note about this media
    thumbnail_path  TEXT,                  -- For video thumbnails
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);

-- Notes Table
-- Standalone notes — no link, no media required (but can be associated)
CREATE TABLE IF NOT EXISTS notes (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    link_id     TEXT REFERENCES links(id) ON DELETE SET NULL,
    media_id    TEXT REFERENCES media(id) ON DELETE SET NULL,
    title       TEXT,
    content     TEXT NOT NULL,             -- The note body (plain text or markdown)
    is_pinned   INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

-- Mindmaps Table
-- A mindmap is a JSON graph stored as a single blob
-- The frontend (Reactflow) owns the graph format; Rust just stores/retrieves it
CREATE TABLE IF NOT EXISTS mindmaps (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title       TEXT NOT NULL,
    graph_data  TEXT NOT NULL,             -- JSON blob: {nodes: [...], edges: [...]}
    thumbnail   TEXT,                      -- Base64 PNG snapshot for preview cards
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

-- Indexes — Always add indexes on foreign keys and frequently queried columns
CREATE INDEX IF NOT EXISTS idx_links_user_id ON links(user_id);
CREATE INDEX IF NOT EXISTS idx_links_category ON links(category);
CREATE INDEX IF NOT EXISTS idx_media_user_id ON media(user_id);
CREATE INDEX IF NOT EXISTS idx_media_link_id ON media(link_id);
CREATE INDEX IF NOT EXISTS idx_notes_user_id ON notes(user_id);
CREATE INDEX IF NOT EXISTS idx_mindmaps_user_id ON mindmaps(user_id);
CREATE INDEX IF NOT EXISTS idx_link_tags_link_id ON link_tags(link_id);
CREATE INDEX IF NOT EXISTS idx_link_tags_tag_id ON link_tags(tag_id);
CREATE INDEX IF NOT EXISTS idx_oauth_tokens_user_id ON oauth_tokens(user_id);
